### ISSUE TITLE
AssertionError in depositOnTray1

### ISSUE THREAD

**Issue by nano-meter** [Figment-Gprt/ariac-competition#1]
After starting a competition:
```
1. rosrun osrf_gear gear.py -f "/home/user/catkin_ws/install/share/osrf_gear/config/comp_conf1.yaml" ~/catkin_ws/src/ariac-competition-master/config/figment_gear_conf.yaml
2. rosrun figment_ariac scheduler_plan
```

I receive the following error after the arm puts a part on the tray:
```
[INFO] [1505216798.515257, 43.334000]: [ExecBin][STEP10] - Move Wait a bit above
[INFO] [1505216798.516786, 43.335000]: [ExecutePart]: move_wait_above_part: [-0.5    0.162  0.724]
[INFO] [1505216798.517555, 43.335000]: [go_to_position_a_bit_above_part] world_position_above_part = [-0.50024870454131831, 0.16198972636970937, 0.97403601671434559]
[INFO] [1505216798.518185, 43.335000]: [depositOnTray1] dx_base:0.128428315338; dy_base=2.15443488791; angle_var: 17.6027742666; angle_var_rad: 0.307226368438; T1: 2.08927559625; T2: 1.97357559625; h_base_piece 0.0208639832857; h_base_imaginary: 0.0867510167143; H1: 0.0412489832857; adhust: True
Traceback (most recent call last):
  File "/home/user/catkin_ws/src/ariac-competition-master/bin/scheduler_plan", line 7, in <module>
    figment_ariac.scheduler_plan.main()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/scheduler_plan.py", line 65, in main
    comp_class.start_plan_and_execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/competition.py", line 52, in start_plan_and_execute
    self.scheduler.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/scheduler.py", line 217, in execute
    status = execute_part.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 1373, in execute
    success = self.execute_bin(part_origin)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 1362, in execute_bin
    success = exec_bin.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 838, in execute
    adjust=True)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 1049, in move_wait_above_part
    adjust=adjust)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/arm_actions.py", line 121, in go_to_position_a_bit_above_part
    world_position_above_part, world_orientation, part_type, adjust=adjust)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/ik_solution.py", line 168, in depositOnTray1
    _,_,_,A2,B2,C2 = solve(a=T3, b=UP_ARM, c=FORE_ARM)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/trianglesolver.py", line 126, in solve
    a,b,c,A,B,C = sss(a,b,c)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/trianglesolver.py", line 50, in sss
    assert d + e > f and e + f > d and f + d > e
AssertionError
```

**Comment by Figment-Gprt** [comment]
Hi nano-meter, the branch that we pushed here was not the latest, sorry for that. I updated to the latest code just now. Can you execute again? 
Thanks!

**Comment by nano-meter** [comment]
I tried it again, but the problem is still present in move_towards_piece_on_belt, more accurately in solverBelt, I put some debug prints in the code:
```
[ExecuteBeltPart]: STEP 3 

[INFO] [1507642424.553700, 10.842000]: logical_camera_belt_1_frame is in transforms_dynamic[world]
[-0.0064421654529422875, -0.00742541733337992, 0.8017414805942987]

[INFO] [1507642424.554381, 10.842000]: [ASSERTERRORDEBUG] T3: 1.24947062966; UP_ARM: 0.6127; FORE_ARM: 0.5716; T2: -1.21517178221; H1: 0.290747990734; A1: 1.33594649837; B1: 0.23484982842;

Traceback (most recent call last):
  File "/home/user/catkin_ws/src/ariac-competition-master/bin/scheduler_plan", line 7, in <module>
    figment_ariac.scheduler_plan.main()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/scheduler_plan.py", line 65, in main
    comp_class.start_plan_and_execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/competition.py", line 52, in start_plan_and_execute
    self.scheduler.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/scheduler.py", line 217, in execute
    status = execute_part.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 1377, in execute
    success = self.execute_belt(part_origin)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 1355, in execute_belt
    success = exec_belt.execute()
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 109, in execute
    part_world_tf_time, part_type)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/execution.py", line 947, in move_towards_piece_on_belt
    list_joint_values = solverBelt(part_world_position, part_world_orientation, part_type)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/ik_solution.py", line 125, in solverBelt
    _,_,_,A2,B2,C2 = solve(a=T3, b=UP_ARM, c=FORE_ARM)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/trianglesolver.py", line 126, in solve
    a,b,c,A,B,C = sss(a,b,c)
  File "/home/user/catkin_ws/src/ariac-competition-master/src/figment_ariac/gprt/trianglesolver.py", line 50, in sss
    assert d + e > f and e + f > d and f + d > e
AssertionError
```
It seems like T3 > UP_ARM + FORE_ARM so the assert fails.

**Comment by nano-meter** [comment]
After updating to gazebo 7.8 this issue no longer present.
